name: Create Localization Help Request

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to compare to (last by default)'
        type: string
        default: '527338889727a69764748468e7c4c62993f00716'
        required: true
      template:
        description: 'Custom YAML template for Markdown (if needed)'
        type: string
        default: 'scripts/template.yml'
        required: true
      disable-mentions:
        description: 'Print mentions as string'
        type: choice
        options:
        - 'True'
        - 'False'
        default: 'False'
        required: true
      js-patch:
        description: 'use git diff for JSON templates (for large repos)'
        required: true
        type: choice
        options:
        - 'True'
        - 'False'
        default: 'False'

jobs:
  call-external-python-action:
    runs-on: ubuntu-latest
    outputs:
      comments: ${{ steps.run_action.outputs.comments }}
      issue_number: ${{ steps.create_issue.outputs.number }}

    steps:
      - name: Checkout your own repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Run Python Action from external repo
        id: run_action
        uses: Knutschbert/create-localization-issue@main
        with:
          base-dir: "assets/locales"
          base-file: "en.json"
          branch: ${{ github.ref }}
          commit: ${{ github.event.inputs.commit }}
          # maintainers: ""
          template: ${{ github.event.inputs.template }}
          disable-mentions: ${{ github.event.inputs.disable-mentions }}
          js-patch: ${{ github.event.inputs.js-patch }}
      # - name: Print outputs
      #   run: echo "Title ${{ steps.run_action.outputs.issue-title }} Comments ${{ toJSON(steps.run_action.outputs.comments) }}"
      - name: Create issue
        id: create_issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: ${{ steps.run_action.outputs.issue-title }}
          body: ${{ steps.run_action.outputs.issue-body }}
          labels: |
            localization, automated, help wanted
  
  create-issue-comments:
    runs-on: ubuntu-latest
    needs: call-external-python-action
    strategy:
      matrix:
        comment: ${{ fromJSON(needs.call-external-python-action.outputs.comments) }}
    
    steps:
      - name: create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ needs.call-external-python-action.outputs.issue_number }}
          body: ${{ fromJSON(matrix.comment) }}
